version: '3.9'
networks:
  app-tier:
    driver: bridge
services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - app-tier
  kafka:
    image: 'bitnami/kafka:latest'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    networks:
      - app-tier
  mongo:
    image: mongo
    restart: always
    networks:
      - app-tier
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password123
  products:
    build: .
    networks:
      - app-tier
    depends_on:
      - kafka
      - mongo
    ports:
      - 8081:8081
    environment:
      DB_USER: root
      DB_PASSWORD: password123
      DB_URI: mongodb://root:password123@mongo:27017/
    volumes:
      - .:/app
      - /app/node_modules